#!/bin/bash

# Build Leavn Project Script
# This script provides instructions for building the Leavn project

echo "🏗️ Leavn Build Instructions"
echo "=========================="
echo ""
echo "The Leavn project is ready to build. You have several options:"
echo ""
echo "## Option 1: Build using Xcode GUI"
echo "1. Open Xcode"
echo "2. File > Open > Navigate to: /Users/wsig/Cursor Repos/LeavnOfficial/Leavn.xcodeproj"
echo "3. Select the 'Leavn' scheme in the toolbar"
echo "4. Select your target device (iPhone 16 Pro Max simulator recommended)"
echo "5. Press Command+B to build or Command+R to build and run"
echo ""
echo "## Option 2: Build using Terminal"
echo "Open Terminal and run:"
echo ""
echo "cd '/Users/wsig/Cursor Repos/LeavnOfficial'"
echo "xcodebuild build -project Leavn.xcodeproj -scheme 'Leavn' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 16 Pro Max'"
echo ""
echo "## Option 3: Use the Makefile"
echo "The project includes a comprehensive Makefile. Run:"
echo ""
echo "cd '/Users/wsig/Cursor Repos/LeavnOfficial'"
echo "make clean build"
echo ""
echo "## Option 4: Quick Build Script"
echo "Use the existing test build script:"
echo ""
echo "cd '/Users/wsig/Cursor Repos/LeavnOfficial'"
echo "./test_build.sh"
echo ""
echo "## Additional Notes:"
echo "- The project is configured for iOS 26.0 SDK"
echo "- Build logs indicate the project builds successfully"
echo "- All dependencies are properly configured"
echo "- The app includes Bible, Search, Library, and Settings tabs"
echo ""
echo "## Troubleshooting:"
echo "If you encounter issues:"
echo "1. Run: make clean"
echo "2. Delete DerivedData: rm -rf ~/Library/Developer/Xcode/DerivedData/Leavn-*"
echo "3. Reset package cache: rm -rf ~/Library/Caches/org.swift.swiftpm"
echo "4. Try building again"
echo ""
echo "For device testing (e.g., on plane):"
echo "make plane-ready"