name: Leavn
options:
  bundleIdPrefix: com.leavn
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

fileGroups:
  - Core
  - Leavn
  - LeavnTests
  - Resources
  - Scripts

packages:
  LeavnCore:
    path: Core/LeavnCore
  LeavnModules:
    path: Core/LeavnModules
    
settings:
  base:
    SWIFT_VERSION: "6.2"
    ENABLE_PREVIEWS: "YES"
    DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    PRODUCT_NAME: "Leavn"

targets:
  Leavn:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Leavn/Platform/iOS
      - path: Leavn/Sources
      - path: Shared
    resources:
      - path: Resources/Assets.xcassets
    dependencies:
      - package: LeavnCore
        products:
          - LeavnCore
          - LeavnServices
          - NetworkingKit
          - PersistenceKit
          - AnalyticsKit
          - DesignSystem
      - package: LeavnModules
        products:
          - LeavnBible
          - LeavnSearch
          - LeavnLibrary
          - LeavnSettings
          - LeavnCommunity
          - AuthenticationModule
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.leavn.app
        INFOPLIST_FILE: Leavn/Platform/iOS/Info.plist
        CODE_SIGN_ENTITLEMENTS: Leavn/Platform/iOS/Leavn-iOS.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SUPPORTS_MACCATALYST: "NO"
    scheme:
      testTargets:
        - LeavnTests
      gatherCoverageData: true

  LeavnTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LeavnTests
    dependencies:
      - target: Leavn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.leavn.tests

schemes:
  Leavn:
    build:
      targets:
        Leavn: all
    test:
      targets:
        - LeavnTests
      gatherCoverageData: true
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release