name: Leavn
options:
  bundleIdPrefix: com.leavn
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: 6.0
    ALWAYS_SEARCH_USER_PATHS: NO
    MARKETING_VERSION: 1.0.0
    CURRENT_PROJECT_VERSION: 1

packages:
  LeavnCore:
    path: Packages/LeavnCore
  LeavnModules:
    path: Modules

targets:
  # iOS App - Optimized for iPhone 16 Pro Max
  Leavn:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 18.0
    sources:
      - path: Leavn
        excludes:
          - "Platform/macOS/**"
          - "Platform/visionOS/**"
          - "Platform/watchOS/**"
          - "Platform/tvOS/**"
    settings:
      base:
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos"
        TARGETED_DEVICE_FAMILY: "1,2"  # iPhone and iPad
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.leavn.app
        PRODUCT_NAME: Leavn
        PRODUCT_DISPLAY_NAME: Leavn
        INFOPLIST_FILE: Leavn/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Leavn/Leavn.entitlements
        ENABLE_PREVIEWS: YES
        SWIFT_STRICT_CONCURRENCY: complete
        SUPPORTS_MACCATALYST: YES
        DERIVE_MACCATALYST_PRODUCT_BUNDLE_IDENTIFIER: NO
        PRODUCT_BUNDLE_IDENTIFIER[sdk=macosx*]: com.leavn.app.catalyst
        CODE_SIGN_STYLE: Automatic
        ENABLE_HARDENED_RUNTIME: YES
        ENABLE_APP_SANDBOX: YES
        # iPhone 16 Pro Max Optimizations
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: YES
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        ASSETCATALOG_COMPILER_OPTIMIZATION: space
        # Advanced Display Support
        ENABLE_USER_SCRIPT_SANDBOXING: YES
        SWIFT_EMIT_LOC_STRINGS: YES
        # Performance Optimizations
        LLVM_LTO: YES_THIN
        SWIFT_COMPILATION_MODE: wholemodule
        DEAD_CODE_STRIPPING: YES
        # Metal Performance Shaders for GPU acceleration
        MTL_ENABLE_DEBUG_INFO: NO
        MTL_FAST_MATH: YES
    info:
      path: Leavn/Info.plist
      properties:
        CFBundleDisplayName: Leavn
        CFBundleName: Leavn
        CFBundleShortVersionString: 1.0.0
        CFBundleVersion: 1
        LSRequiresIPhoneOS: true
        UIRequiredDeviceCapabilities: ["armv7", "metal"]
        UISupportedInterfaceOrientations: 
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UILaunchStoryboardName: LaunchScreen
        # iPhone 16 Pro Max Specific Features
        UIStatusBarStyle: UIStatusBarStyleDefault
        UIViewControllerBasedStatusBarAppearance: true
        UIUserInterfaceStyle: Automatic
        # Privacy Usage Descriptions
        NSCameraUsageDescription: "Leavn uses the camera to scan Bible verse references and create study content."
        NSMicrophoneUsageDescription: "Leavn uses the microphone for voice notes and prayer recordings."
        NSLocationWhenInUseUsageDescription: "Leavn uses location to find nearby churches and Bible study groups."
        NSUserTrackingUsageDescription: "This helps us provide personalized Bible study recommendations."
        # Background Modes for Sync
        UIBackgroundModes:
          - background-processing
          - background-fetch
          - remote-notification
        # App Transport Security
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: false
          NSExceptionDomains:
            bible-api.com:
              NSExceptionAllowsInsecureHTTPLoads: false
              NSExceptionMinimumTLSVersion: TLSv1.2
        # CloudKit
        NSUbiquitousContainers:
          iCloud.com.leavn.app:
            NSUbiquitousContainerName: "Leavn Bible Study"
            NSUbiquitousContainerSupportedFolderLevels: Any
    resources:
      - Leavn/Assets.xcassets
    dependencies:
      - package: LeavnCore
        product: DesignSystem
      - package: LeavnCore
        product: LeavnServices
      - package: LeavnModules
        product: LeavnBible
      - package: LeavnModules
        product: LeavnSearch
      - package: LeavnModules
        product: LeavnLibrary
      - package: LeavnModules
        product: LeavnSettings
      - package: LeavnModules
        product: LeavnCommunity
      - package: LeavnModules
        product: AuthenticationModule

schemes:
  Leavn:
    build:
      targets:
        Leavn: all
    run:
      config: Debug
      commandLineArguments:
        "-com.apple.CoreData.SQLDebug": "1"
        "-com.apple.CoreData.Logging.stderr": "1"
      environmentVariables:
        OS_ACTIVITY_MODE: disable
        CFNETWORK_DIAGNOSTICS: "3"
    test:
      config: Debug
      gatherCoverageData: true
      coverageTargets:
        - Leavn
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
