name: Leavn
options:
  bundleIdPrefix: com.leavn
  createIntermediateGroups: true

settings:
  base:
    SWIFT_VERSION: 6.0
    ALWAYS_SEARCH_USER_PATHS: NO

packages:
  LeavnCore:
    path: Packages/LeavnCore
  LeavnModules:
    path: Modules

targets:
  Leavn:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: 18.0
    sources:
      - path: Leavn
        excludes:
          - "Platform/macOS/**"
          - "Platform/visionOS/**"
          - "Platform/watchOS/**"
          - "Platform/tvOS/**"
    settings:
      base:
        # Explicit iOS settings
        SDKROOT: iphoneos
        SUPPORTED_PLATFORMS: "iphonesimulator iphoneos"
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"

        # App settings
        PRODUCT_BUNDLE_IDENTIFIER: com.leavn.app
        PRODUCT_NAME: Leavn
        PRODUCT_DISPLAY_NAME: Leavn
        INFOPLIST_FILE: Leavn/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_ENTITLEMENTS: Leavn/Leavn.entitlements
        ENABLE_PREVIEWS: YES
        SWIFT_STRICT_CONCURRENCY: complete
        ENABLE_TESTING_SEARCH_PATHS: YES
        CLANG_ANALYZER_NONNULL: YES
        CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION: YES_AGGRESSIVE
        GCC_WARN_ABOUT_DEPRECATED_FUNCTIONS: YES
        GCC_WARN_ABOUT_DEPRECATED_OBJC_IMPLEMENTATIONS: YES
        GCC_WARN_ABOUT_STRICT_SELECTOR_MATCH: YES
        GCC_WARN_UNUSED_VARIABLE: YES
        GCC_WARN_UNUSED_FUNCTION: YES
        GCC_WARN_UNUSED_LABEL: YES
        GCC_WARN_UNUSED_PARAMETER: YES
        GCC_WARN_UNUSED_VALUE: YES
        GCC_WARN_64_TO_32_BIT_CONVERSION: YES
        GCC_WARN_ABOUT_RETURN_TYPE: YES
        GCC_WARN_UNDECLARED_SELECTOR: YES
        GCC_WARN_UNINITIALIZED_AUTOS: YES
        GCC_WARN_SHADOW: YES
        GCC_WARN_SIGN_COMPARE: YES
        GCC_WARN_STRICT_SELECTOR_MATCH: YES
    info:
      path: Leavn/Info.plist
    resources:
      - Leavn/Assets.xcassets
      - Leavn/Preview Content
    dependencies:
      # Core package
      - package: LeavnCore
        product: DesignSystem
      - package: LeavnCore
        product: LeavnServices
      # Feature modules
      - package: LeavnModules
        product: LeavnBible
      - package: LeavnModules
        product: LeavnSearch
      - package: LeavnModules
        product: LeavnLibrary
      - package: LeavnModules
        product: LeavnSettings
      - package: LeavnModules
        product: LeavnCommunity
      - package: LeavnModules
        product: AuthenticationModule

  LeavnTV:
    type: application
    platform: tvOS
    deploymentTarget:
      tvOS: 18.0
    sources:
      - path: Leavn
        excludes:
          - "Leavn/Platform/iOS/**"
          - "Leavn/Platform/macOS/**"
          - "Leavn/Platform/visionOS/**"
          - "Leavn/Platform/watchOS/**"
    info:
      path: Leavn/Info-tvOS.plist
    settings:
      base:
        ASSETCATALOG_COMPILER_APPICON_NAME: "App Icon & Top Shelf Image"
        ASSETCATALOG_COMPILER_LAUNCHIMAGE_NAME: LaunchImage
        TARGETED_DEVICE_FAMILY: 3
        TVOS_DEPLOYMENT_TARGET: 18.0
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/Frameworks"
    resources:
      - Leavn/Assets.xcassets
      - Leavn/Preview Content
    dependencies:
      # Feature modules
      - package: LeavnModules
        product: LeavnBible
      - package: LeavnModules
        product: LeavnSearch
      - package: LeavnModules
        product: LeavnLibrary
      - package: LeavnModules
        product: LeavnSettings
      - package: LeavnModules
        product: LeavnCommunity
      - package: LeavnModules
        product: AuthenticationModule
