name: Leavn
options:
  bundleIdPrefix: com.leavn
  deploymentTarget:
    iOS: "18.0"
  developmentLanguage: en
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

fileGroups:
  - Core
  - Leavn
  - LeavnTests
  - Resources
  - Scripts

# packages:
#   LeavnCore:
#     path: Core/LeavnCore
#   LeavnModules:
#     path: Modules
    
settings:
  base:
    SWIFT_VERSION: "6.2"
    ENABLE_PREVIEWS: "YES"
    DEVELOPMENT_TEAM: "$(DEVELOPMENT_TEAM)"
    CODE_SIGN_STYLE: Automatic
    CODE_SIGN_IDENTITY: "Apple Development"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"
    PRODUCT_NAME: "Leavn"

targets:
  Leavn:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: Leavn
        excludes:
          - "**/*.disabled"
          - "**/Package.swift.disabled"
          # Exclude all non-iOS platform code
          - "Platform/macOS/**"
          - "Platform/watchOS/**"
          - "Platform/visionOS/**"
          - "Platform/tvOS/**"
          # Exclude iOS platform files that might conflict
          - "Platform/iOS/LaunchScreen.storyboard"
          - "Platform/iOS/Info.plist"
          - "Platform/iOS/ContentView.swift"
          - "Platform/iOS/LeavnApp.swift"
          # Exclude tvOS Info.plist
          - "Info-tvOS.plist"
          # Exclude duplicate Assets
          - "Assets 2.xcassets"
          - "Assets_2.xml"
      - path: Modules
        excludes:
          - "**/*.disabled"
          - "**/Package.swift.disabled"
          - "**/Package.swift"
          # Temporarily disable problematic modules
          - "Settings/**"
          - "Community/**"
          - "Search/**"
          - "Library/**"
          - "Onboarding/**"
          - "Discover/**"
          - "Map/**"
          - "Authentication/**"
      - path: Shared
        excludes:
          - "**/*.disabled"
          - "Components/MainTabView.swift"
      # Temporarily disable Core to avoid conflicts
      # - path: Core/LeavnCore/Sources/LeavnCore
      #   excludes:
      #     - "**/*.disabled"
      #     - "**/Package.swift"
      # - path: Core/LeavnCore/Sources/DesignSystem
      #   excludes:
      #     - "**/*.disabled"
      #     - "**/Package.swift"
    resources:
      # Use only Leavn/Assets.xcassets, not Resources/Assets.xcassets
      - path: Leavn/Assets.xcassets
      - path: Leavn/GoogleService-Info.plist
      - path: Leavn/Info.plist
        buildPhase: none
      - path: Leavn/LaunchScreen.storyboard
    # dependencies removed - all code is now directly included
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.leavn.app
        INFOPLIST_FILE: Leavn/Info.plist
        CODE_SIGN_ENTITLEMENTS: Leavn/Leavn.entitlements
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        TARGETED_DEVICE_FAMILY: "1,2"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SUPPORTS_MACCATALYST: "NO"
    scheme:
      testTargets:
        - LeavnTests
      gatherCoverageData: true

  LeavnTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - LeavnTests
    dependencies:
      - target: Leavn
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.leavn.tests

schemes:
  Leavn:
    build:
      targets:
        Leavn: all
    test:
      targets:
        - LeavnTests
      gatherCoverageData: true
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release