import Foundation
import CoreData

// MARK: - UserProfile
@objc(UserProfile)
public class UserProfile: NSManagedObject {
    // Properties are auto-generated by Core Data due to codeGenerationType="category"
}

// MARK: - UserPreferences
@objc(UserPreferences)
public class UserPreferences: NSManagedObject {
    // Properties are auto-generated by Core Data due to codeGenerationType="category"
}

// MARK: - ReadingProgress
@objc(ReadingProgress)
public class ReadingProgress: NSManagedObject {
    // Properties are auto-generated by Core Data due to codeGenerationType="category"
}

// MARK: - Bookmark
@objc(Bookmark)
public class Bookmark: NSManagedObject {
    // Properties are auto-generated by Core Data due to codeGenerationType="category"
}

// MARK: - Note
@objc(Note)
public class Note: NSManagedObject {
    // Properties are auto-generated by Core Data due to codeGenerationType="category"
}

// MARK: - ReadingSession
@objc(ReadingSession)
public class ReadingSession: NSManagedObject {
    // Properties are auto-generated by Core Data due to codeGenerationType="category"
}

// MARK: - Fetch Request Extensions
// fetchRequest() methods are auto-generated by Core Data for entities with codeGenerationType="category"