name: Release Management

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Release Please
        id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: LeavnSuperOfficial
          
      - name: Generate changelog
        if: ${{ steps.release.outputs.release_created }}
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          
      - name: Update release notes
        if: ${{ steps.release.outputs.release_created }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          body_path: CHANGELOG.md
          
  deploy-release:
    name: Deploy Release
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    uses: ./.github/workflows/deploy.yml
    with:
      lane: release
    secrets: inherit