name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  DEVELOPER_DIR: /Applications/Xcode_16.0.app/Contents/Developer

jobs:
  lint:
    name: Lint
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Run SwiftLint
      run: swiftlint lint --reporter github-actions-logging

  test-core:
    name: Test Core Modules
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s $DEVELOPER_DIR
      
    - name: Test LeavnCore
      run: |
        cd Core/LeavnCore
        swift test
        
    - name: Test LeavnModules
      run: |
        cd Core/LeavnModules
        swift test

  build-ios:
    name: Build iOS
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s $DEVELOPER_DIR
      
    - name: Cache SPM packages
      uses: actions/cache@v3
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Install xcbeautify
      run: brew install xcbeautify
      
    - name: Generate Xcode Project
      run: |
        if [ -f "project.yml" ]; then
          brew install xcodegen
          xcodegen generate
        fi
        
    - name: Build iOS App
      run: |
        xcodebuild build \
          -scheme Leavn-iOS \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -derivedDataPath .build \
          | xcbeautify

  build-macos:
    name: Build macOS
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s $DEVELOPER_DIR
      
    - name: Cache SPM packages
      uses: actions/cache@v3
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Install xcbeautify
      run: brew install xcbeautify
      
    - name: Generate Xcode Project
      run: |
        if [ -f "project.yml" ]; then
          brew install xcodegen
          xcodegen generate
        fi
        
    - name: Build macOS App
      run: |
        xcodebuild build \
          -scheme Leavn-macOS \
          -configuration Debug \
          -destination 'platform=macOS' \
          -derivedDataPath .build \
          | xcbeautify

  test-ios:
    name: Test iOS
    runs-on: macos-14
    needs: build-ios
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s $DEVELOPER_DIR
      
    - name: Cache SPM packages
      uses: actions/cache@v3
      with:
        path: |
          .build
          ~/Library/Developer/Xcode/DerivedData
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
          
    - name: Install xcbeautify
      run: brew install xcbeautify
      
    - name: Generate Xcode Project
      run: |
        if [ -f "project.yml" ]; then
          brew install xcodegen
          xcodegen generate
        fi
        
    - name: Run iOS Tests
      run: |
        xcodebuild test \
          -scheme Leavn-iOS \
          -configuration Debug \
          -destination 'platform=iOS Simulator,name=iPhone 15 Pro' \
          -derivedDataPath .build \
          -enableCodeCoverage YES \
          | xcbeautify
          
    - name: Upload Coverage
      uses: codecov/codecov-action@v3
      with:
        xcode: true
        xcode_archive_path: .build/Build/Products/Debug-iphonesimulator